services:
  lipupini:
    build:
      context: ../../../..
      dockerfile: ./system/deploy/docker/php-builtin/Dockerfile
    ports:
      - "4000:4000"
    restart: unless-stopped
    volumes:
      - ../../../collection:/app/collection:rw
